#steps:
#- uses: actions/checkout@v3
#- uses: actions/setup-java@v2
#  with:
#    distribution: 'zulu'
#    java-version: '11'
#- uses: subosito/flutter-action@v2
#  with:
#    flutter-version: '3.0.5'
#- run: flutter pub get
#- run: flutter test
#- run: flutter build apk
#- run: flutter build appbundle

name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
        name: Checkout code
        uses: actions/checkout@v3

        name: Setup Java
        uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'

        name: Install Flutter
        uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.3.2'
            channel: 'stable'

        name: Get Flutter Packages
        run: flutter pub get

        name: Build APK
        run: flutter build apk

        #name: Build App Bundle
        #run: flutter build appbundle
        
        name: Run Unit Tests
        run: flutter test --coverage

        name: Upload Unit Test Results To codecov.io
        uses: codecov/codecov-action@v1.2.2
          with:
            token: ${{secrets.CODECOV_TOKEN}}
            file: coverage/lcov.info

        name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v1
          with:
            api-level: 29
            script: flutter test integration_test

        name: Upload APK
        uses: actions/upload-artifact@v3
          with:
            name: release-apk
            path: build/app/outputs/apk/release/app-release.apk        

        name: Upload Screenshots
        uses: actions/upload-artifact@v3
          with:
            name: Test result screenshots
            path: screenshots/*.png